CREATE TABLE speed_schedule_events (
    event_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT REFERENCES speed_schedule_users(username) ON DELETE CASCADE NOT NULL,
    event_name TEXT NOT NULL,
    duration INTEGER NOT NULL,
    notes TEXT
);